on: push
jobs:
   testing-action:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Send a Slack Message
          uses: ./.github/actions/slack
          with:
            slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
            message: Hello  Slack
        - name: Open Github Issue 77
          
        - uses: ./.github/actions/issue
          id: issue
          with: 
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Title
            body: Body
            assignees: |
             SnehaDavari
             
        - run: |
            echo ${{ steps.issue.outputs.issue }}
             
        - run: |
            echo ${{ steps.issue.outputs.issue }} 
            chmod +x ./.github/actions/hello-docker/entrypoint.sh
        - uses: ./.github/actions/hello-docker
          id: hello
          with:
             who-to-greet: "World"
        - run: |
            echo "Time: ${{ steps.hello.outputs.time }}"
            echo $Hello