on: push
jobs:
   testing-action:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1    
        - name: Open Github Issue 77
          uses: SnehaDavari/open-issue@v1.0.0
          id: issue
          with: 
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Title
            body: Body
            assignees: | 
             SnehaDavari 

        - run: |
            echo ${{ steps.issue.outputs.issue }} 
        - uses: ./.github/actions/hello
          id: hello
          with:
             who-to-greet: "World"
        - run: |
            echo "Time: ${{ steps.hello.outputs.time }}"
            echo $Hello
                  
       