on: push
jobs:
   testing-action:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Send a Slack Message
          uses: ./.github/actions/slack
          with:
            slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
            message: Hello  Slack
        - name: Open Github Issue 77
          uses: ./.github/actions/issue
          id: issue
          with: 
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Title
            body: Body
            assignees: |
             SnehaDavari
                  
       